spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:tcp://localhost/C:\Users\82106\Desktop\taekwan\h2 database\h2\db/redis-test
    username: sa
    password: 123

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

test:
  data:
    redis:
      host: localhost
      port: 6379
      password: redistest


server:
  port: 8081